version: '3.8'
services:
  frontend:
    build: .
    container_name: ornsoar-frontend
    ports:
      - "3001:3000"  # Aapka frontend jis port pe chalta ho
    env_file:
      - .env
    restart: always